config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'favorites/update'
  resources :purchases
  
  resources :announcements
  devise_for :sellers, path: 'sellers', controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "sellers/registrations",sessions: "sellers/sessions"}
  devise_for :buyers, path: 'buyers', controllers: { registrations: "buyers/registrations",sessions: "buyers/sessions", omniauth_callbacks: "buyers/omniauth_callbacks"}
  
  #home routes
  root 'home#index'
  get 'announcements/search' , to:'announcement#search'
  get '/about', to: 'home#about'

  resources :searches

 

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end



  #buyer route
  get '/buyer/home', to: 'buyer#home'
  get '/buyer/profile', to: 'buyer#profile'
  get '/buyer/my_purchases', to: 'buyer#my_purchases'
  get '/buyer/my_favorites', to: 'buyer#my_favorites'
  get '/buyer/my_messages', to: 'chat#index'




  #seller route
  get '/seller/home', to: 'seller#home'
  get '/seller/profile', to: 'seller#profile'
  get '/seller/my_objects', to: 'seller#my_objects'
  get '/seller/my_messages', to: 'chat#index'
  get '/seller/my_orders', to: 'seller#my_orders'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/announcement.rb
class Announcement < ApplicationRecord

    mount_uploader :image, ImageUploader
    serialize :image, JSON
    belongs_to :seller, optional: true
    has_one  :purchase
    has_one  :order
    validates :title, :category, :price, presence:true
    validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed."}, presence:true
    validates :title, length: {maximum: 140, too_long: "%{count} characters is the maximum allowed"}
    validates :price, length: {maximum: 10}
    validates :seller_id, presence:true

    CATEGORY = %w{Eletronics Car Telephony Tools VideoGames Books HomeAndKitchen Computer Clothing}
    CONDITION = %w{New Excellent Mint Used Poor }
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_seller!, except: [:index, :show]
  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    if(buyer_signed_in?)
      @favorite_exists = Favorite.where(announcement: @announcement, buyer: current_buyer) == [] ? false : true
    end
  end

  # GET /announcements/new
  def new
    @announcement = current_seller.announcements.build
    
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = current_seller.announcements.build(announcement_params)

    @announcement.seller = current_seller

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

 def search
  @announcements = Announcement.where("title = ?", params[:title])

 end


  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def announcement_params
      params.require(:announcement).permit(:title, :category, :description, :condition, :price, :image, :sold)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper

    def announcement_author(announcement)
        seller_signed_in? && current_seller.id == announcement.seller.id
    end
end

app/views/announcements/_form.html.erb
 
 
<div class="columns">
  <div class="column is-8 is-centered">
    <%= simple_form_for @announcement, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Category</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :category, collection: Announcement::CATEGORY, prompt: "Select Category" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
          </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Condition</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condition, collection: Announcement::CONDITION, prompt: "Select condition" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
         </div>

        <div class="columns">
        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input announcement-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
            </div>
           <div class="field column is-4"></div>
               <label class="label">Sold</label>
              <div class="control has-icons-left">
                <span class="select">
                   <%= f.select :sold,  [['None', false], ['Yes', true]] %>
                </span>
              </div>
            </div>
          </div>
          </div>
          <output id="list"></output>
        <hr />
       

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', announcements_path, class:'button is-light' %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/announcements/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Announcement
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', announcement: @announcement %>
</div>

app/views/announcements/index.html.erb
<% content_for :header do %>

      <h1 class="title">
        Browse the latest announcements on Second Hand
      </h1>
<% end %>
<%= link_to "Search", new_search_path %>

<p id="notice"><%= notice %></p>


<div class="announcement-index-grid pt4">
  <% @announcements.each do |announcement| %>

    <div class="announcement border-light">
      <div class="announcement-thumb">
      <%= link_to image_tag(announcement.image_url(:thumb)), announcement %>

      <% if announcement.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= announcement.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to announcement.title, announcement %></h3>

      <p class="has-text-gray fg pt1">Sold by <%=  %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(announcement.price) %></p>

       <%= link_to 'Delete', announcement, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <% if announcement_author(announcement) %>
         <%= link_to 'Edit', edit_announcement_path(announcement), class: "button is-small" %>
         <%= link_to 'Delete', announcement, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/announcements/new.html.erb
<% content_for :header do %>
    <div class="container">
      <h1 class="title">
        Insert a new announcement
      </h1>
    </div>
<% end %>

<div class="pv4">
  <%= render 'form', announcement: @announcement %>
</div>

app/views/announcements/search.html.erb
 
 <section class="section">
    <div class="container is-fluid">
    <div class = "notification">
      <h1 class="title">Cerca tra gli annunci</h1>
      <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Cosa cerchi?</label>
      </div>
    <form action = "/searches" accept-charset= "UTF-8" data-remote = "true" method="post">
      <div class="field-body">
    <div class="field">
      <p class="control is-expanded has-icons-left">
        <input class="input" type="text"  name= "search[title]" placeholder="titolo">
      </p>
    </div>
    <div class="field-label is-normal">
        <label class="label">Categoria</label>
    </div>
    <div class="field">
    <div class="control is-expanded">
        <div class="select is-fullwidth">
        <select name= "search[category]">
            <option>Telefonia</option>
            <option>Car</option>
            <option>Abbigliamento</option>
            <option>Elettronics</option>
        </select>
        </div>
    </div>
    </div>
    <div class="field-label is-normal">
      <label class="label">Dove</label>
    </div>
    <div class="field">
      <p class="control is-expandeds">
        <input class="input" type="text" placeholder="Email">
      </p>
    </div>
    <div class="field is-grouped">
  <div class="control">
  <input class="button" type="submit" value="Create">

  </div>
  </div>
  </div>
</div>

</form>

app/views/announcements/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section announcement-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @announcement.title %></h1>

      <div class="feature-image">
         <% if @announcement.image_url %>
         <%= image_tag(@announcement.image_url(:default)) %>
         <% end %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description</h3>
      <%= @announcement.description %>


      <h3 class="subtitle is-4 pt5">Product Specs</h3>

      <table class="table is-narrow">
        <% if @announcement.condition %>
        <tr>
          <td class="has-text-weight-bold">Condition:</td>
          <td><%= @announcement.condition %></td>
        </tr>
        <% end %>

        <% if @announcement.category %>
          <tr>
            <td class="has-text-weight-bold">Category:</td>
            <td><%= @announcement.category %></td>
          </tr>
        <% end %>
      
      </table>
    </div>
    </div>
    <% if buyer_signed_in?%>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
      <%=link_to favorite_text, favorites_update_path(announcement: @announcement), id:'favorite_link', remote: true %>
        <p >Sold by <%= @announcement.seller.username %></p>
        <button class="buy">
        <%= link_to "Acquista #{number_to_currency(@announcement.price)}", new_purchase_path(amount: @announcement.price, announcement: @announcement) ,class:"btn btn-default btn-expanded" %>
        </button>
      </div>
    </div>
     </div>


   <% else %>
  <div class="column is-3 is-offset-1">
  <div class="bg-white pa4 border-radius-3">
    <p >Sold by <%= @announcement.seller.email %></p>
     <% if announcement_author(@announcement) %>
    <%= link_to 'Edit', edit_announcement_path(@announcement), class: 'button' %>
    <% end %>
  </div>
 
  </div>
  <% end%>

</section>