config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'favorites/update'
  resources :purchases
  
  resources :announcements
  devise_for :sellers, path: 'sellers', controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "sellers/registrations",sessions: "sellers/sessions"}
  devise_for :buyers, path: 'buyers', controllers: { registrations: "buyers/registrations",sessions: "buyers/sessions", omniauth_callbacks: "buyers/omniauth_callbacks"}
  
  #home routes
  root 'home#index'
  get 'announcements/search' , to:'announcement#search'
  get '/about', to: 'home#about'

  resources :searches

 

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end



  #buyer route
  get '/buyer/home', to: 'buyer#home'
  get '/buyer/profile', to: 'buyer#profile'
  get '/buyer/my_purchases', to: 'buyer#my_purchases'
  get '/buyer/my_favorites', to: 'buyer#my_favorites'
  get '/buyer/my_messages', to: 'chat#index'




  #seller route
  get '/seller/home', to: 'seller#home'
  get '/seller/profile', to: 'seller#profile'
  get '/seller/my_objects', to: 'seller#my_objects'
  get '/seller/my_messages', to: 'chat#index'
  get '/seller/my_orders', to: 'seller#my_orders'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:stripe_connect]
  

  has_many :notifications, foreign_key: :recipient_id
  has_many :announcements , dependent: :destroy
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  has_many :orders
  has_one_attached :avatar

  validates :username, presence: true
  validates :email, presence: true

  def can_receive_payments?
    uid? && provider? && access_code && publishable_key?
   
  end


  
end

app/controllers/seller_controller.rb
class SellerController < ApplicationController
    before_action :authenticate_seller!


    def home
    end

    def profile
        
    end


    def my_objects
        @announcements = current_seller.announcements


    end

    def my_orders
        @orders = Order.where(seller: current_seller,completed: false)
        @completed = Order.where(seller: current_seller,completed: true)



    end
    





end

app/controllers/sellers/confirmations_controller.rb
# frozen_string_literal: true

class Sellers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/sellers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Sellers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/sellers/passwords_controller.rb
# frozen_string_literal: true

class Sellers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/sellers/registrations_controller.rb
# frozen_string_literal: true

class Sellers::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up) do |seller|
      seller.permit(:email, :password, :password_confirmation, :username)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update) do |seller| 
      seller.permit(:email, :password, :password_confirmation,:username, :current_password, :avatar)
    end
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sellers/sessions_controller.rb
# frozen_string_literal: true

class Sellers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/sellers/unlocks_controller.rb
# frozen_string_literal: true

class Sellers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/seller/home.html.erb
<h1> ciao seller </h1>

app/views/seller/my_objects.html.erb
<% content_for :header do %>
    <div class="container">
      <h1 class="title">
        Announcements created by you
      </h1>
    </div>
<% end %>

<div class="announcement-index-grid pt4">
  <% @announcements.each do |announcement| %>

    <div class="announcement border-light">
      <div class="announcement-thumb">
       <%= link_to image_tag(announcement.image_url(:thumb)), announcement %>


      <% if announcement.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= announcement.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to announcement.title, announcement %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= announcement.seller.username %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(announcement.price) %></p>

      <% if announcement_author(announcement) %>
         <%= link_to 'Edit', edit_announcement_path(announcement), class: "button is-small" %>
         <%= link_to 'Delete', announcement, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/seller/my_orders.html.erb
<% content_for :header do %>
    <div class="container">
      <h1 class="title">
        Orders to be completed
      </h1>
    </div>
<% end %>
<table class="table table-striped">
  <thead class="thead-dark">
     <tr>
       <th colspan="2 ">Description</th>
       <th colspan="1">Purchase id</th>
       <th colspan="1">Buyer email</th>
       <th colspan="1">Buyer username</th>
       <th colspan="1"></th>
      </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.description %><th>
        <td><%= order.announcement.purchase.id%></th>
        <td><%= order.announcement.purchase.buyer.email%></th>
        <td><%= order.announcement.purchase.buyer.username%></th>
        <td><%= link_to 'Edit', edit_order_path(order) , :class=>"btn btn-outline-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
     <div class="container">
      <h1 class="title">
        Orders completed
      </h1>
    </div>
<table class="table table-striped">
  <thead class="thead-dark">
     <tr>
       <th colspan="2 ">Descrizione</th>
       <th colspan="1">Purchase id</th>
       <th colspan="1">Buyer email</th>
       <th colspan="1">Buyer username</th>
       <th colspan="1"></th>
      </tr>
  </thead>
  <tbody>
    <% @completed.each do |completed| %>
      <tr>
        <td><%= completed.description %><th>
        <td><%= completed.announcement.purchase.id%></th>
        <td><%= completed.announcement.purchase.buyer.email%></th>
        <td><%= completed.announcement.purchase.buyer.username%></th>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

app/views/seller/profile.html.erb
<!-- profile page -->
<div class="container">
<div class="columns">
   <div class="column is-2">
    </div>
   <div class="column is-5">
    <div class="card">
       <div class="card-image">
       <figure class="image is-3by3">
       <% if current_seller.avatar.attached? %>
       <a href='#'> <%= image_tag(current_seller.avatar ) %></a>
       <% end %>
      </figure>
  </div>
  <br>
  <br>
   <div id="features" class="card-content">
    <div class="content">
      <p>Username:<%= current_seller.username %> </p>
      <p>Email:<%= current_seller.email %> </p>
    </div>
  </div>
</div>
</div>
<br>
<br>
</div>
</div>