config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'favorites/update'
  resources :purchases
  
  resources :announcements
  devise_for :sellers, path: 'sellers', controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "sellers/registrations",sessions: "sellers/sessions"}
  devise_for :buyers, path: 'buyers', controllers: { registrations: "buyers/registrations",sessions: "buyers/sessions", omniauth_callbacks: "buyers/omniauth_callbacks"}
  
  #home routes
  root 'home#index'
  get 'announcements/search' , to:'announcement#search'
  get '/about', to: 'home#about'

  resources :searches

 

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end



  #buyer route
  get '/buyer/home', to: 'buyer#home'
  get '/buyer/profile', to: 'buyer#profile'
  get '/buyer/my_purchases', to: 'buyer#my_purchases'
  get '/buyer/my_favorites', to: 'buyer#my_favorites'
  get '/buyer/my_messages', to: 'chat#index'




  #seller route
  get '/seller/home', to: 'seller#home'
  get '/seller/profile', to: 'seller#profile'
  get '/seller/my_objects', to: 'seller#my_objects'
  get '/seller/my_messages', to: 'chat#index'
  get '/seller/my_orders', to: 'seller#my_orders'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    @seller = Seller.find(params[:seller])
    return @seller
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
    @announcement = Announcement.find(params[:announcement])
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @announcement = Announcement.find(params[:announcement])

    @purchase = Purchase.new(announcement: @announcement, buyer_id: current_buyer.id, description: @announcement.title,seller_id: @announcement.seller.id )
    key = @announcement.seller.access_code
    Stripe.api_key = key

    token = params[:stripeToken]

    customer = if current_buyer.stripe_id?
                Stripe::Customer.retrieve(current_user.stripe_id)
              else
                Stripe::Customer.create(email: current_buyer.email, source: token)
              end

              payment_intent = Stripe::PaymentIntent.create({
                customer:customer,
                payment_method_types: ['card'],
                amount: @announcement.price.to_i * 100,
                currency: 'eur',
                confirm: true, 
              }, stripe_account: @announcement.seller.uid)

    respond_to do |format|
      if @purchase.save
        #create the notifications
        Order.create(description: "ordine 2",seller: @announcement.seller,announcement: @announcement)
        Notification.create(recipient: @announcement.seller, actor: current_buyer, action: "buy" ,notifiable: @announcement)
        @user = current_buyer
        format.html { redirect_to buyer_my_purchases_path, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  def my_purchases



  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def purchase_params
      params.require(:purchase).permit(:seller_id,:buyer_id, :description)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= form_with model: current_buyer, local: true, url: purchases_url, method: :post, html: { id: "payment-form", class: "stripe-form" }, data: { stripe_key: announcement.seller.publishable_key }  do |form| %>
  <div>
    <label for="card-element" class="label">
      Credit or debit card
    </label>

    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors. -->
    <div id="card-errors" role="alert" class="text-sm text-red-400"></div>
  </div>

  <input type="hidden" name="announcement" value="<%= params[:announcement] %>">

  <button class="purchase">Buy<em></em></button> <%= number_to_currency(params[:amount]) %>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchases</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.description %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<div class="w-1/2 mx-auto">
  <h3 class="mb-2 text-2xl font-bold text-center">You're about to buy <em><%= @announcement.title %> </em></h3>

  <% if buyer_signed_in? %>
  <div class="p-6 border rounded">
    <%= render "form", announcement: @announcement %>
  </div>
  <% else %>
  <div class="p-6 text-center bg-white border rounded">
    <%= link_to "Sign in to back this idea", new_buyer_session_path, class: "btn btn-default" %>
  </div>
  <% end %>
</div>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @purchase.description %>
  <%= @seller.email %>



  
</p>

<%= link_to 'Back', buyer_my_purchases_path %>