config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'favorites/update'
  resources :purchases
  
  resources :announcements
  devise_for :sellers, path: 'sellers', controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "sellers/registrations",sessions: "sellers/sessions"}
  devise_for :buyers, path: 'buyers', controllers: { registrations: "buyers/registrations",sessions: "buyers/sessions", omniauth_callbacks: "buyers/omniauth_callbacks"}
  
  #home routes
  root 'home#index'
  get 'announcements/search' , to:'announcement#search'
  get '/about', to: 'home#about'

  resources :searches

 

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end



  #buyer route
  get '/buyer/home', to: 'buyer#home'
  get '/buyer/profile', to: 'buyer#profile'
  get '/buyer/my_purchases', to: 'buyer#my_purchases'
  get '/buyer/my_favorites', to: 'buyer#my_favorites'
  get '/buyer/my_messages', to: 'chat#index'




  #seller route
  get '/seller/home', to: 'seller#home'
  get '/seller/profile', to: 'seller#profile'
  get '/seller/my_objects', to: 'seller#my_objects'
  get '/seller/my_messages', to: 'chat#index'
  get '/seller/my_orders', to: 'seller#my_orders'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end


  def about
  end

  def login
  end

  def search
  end

end

app/views/home/about.html.erb
<div class="card" >
  <div class="card-body">
      <h3>About</h3>
  </div>
</div>
<br>

<div class="card shadow p-3 mb-5 bg-white rounded">
  <div class="card-body">
      <p> © 2020 Copyright: <%= link_to "Second_Hand",   root_path %> </p>
      <i><small class="text-muted">Version 1.0.0</small></i>
  </div>
</div>

app/views/home/index.html.erb
 
 <section class="section">
    <div class="container is-fluid">
    <section class = "section">
    <% if seller_signed_in? %>
      <h3> Hi Seller now you can start to insert announcements </h3>
      <div class= "column-is-4">
      <div class= "p-6 mt-10 text-gray-900 bg-white rounded shadow-lg">
      <% unless current_seller.can_receive_payments? %>
      <h4 class= "mb-6 text-xl font-semibold leading-none text-gray-900">
     You wont be able to sell items until you register with Stripe!</h4>
      <%= stripe_connect_button %>  
     <% end%>  
    </div>
    </div>
    <div class="columns">
  <div class="column is-4">
  </div>
  <div class="column is-3">
  <div class="card">
  <div class="card-image">
    <figure class="image is-3by2">
      <a href='/sellers/sign_up'> <%= image_tag("seller.png", ) %></a>
    </figure>
  </div>
  <div class="card-content">
    <div class="content">
      <p> Seller</p>
    </div>
    </div>
   </div> 
  </div>
   </div>
     <%elsif buyer_signed_in? %>
     <h3> Hi friend you can now begin shoping! </h3>
     <div class="columns">
     <div class="column is-4">
     </div>
  <div class="column is-3">
  <div class="card">
  <div class="card-image">
    <figure class="image is-3by2">
      <a href='/buyers/sign_up'> <%= image_tag("buyer.png", ) %></a>
    </figure>
  </div>
  <div class="card-content">
    <div class="content">
    <a href="#"> Are you a buyer ?</a>
    </div>
  </div>
   <% else %>
     <h3> GUEST </h3>
    </section>
   </div>
   <br>
   <br>
    <div class="container is-fluid">
    <div class = "notification">
     Hi friend, Second Hand is an application to easy search and buy object sold by other users. If you wanto to start selling click here. Otherwise if you want to buy something click here.
    </div>
   </div>
  <br>
<br>
<div class="columns">
  <div class="column is-2">
  </div>
  <div class="column is-3">
  <div class="card">
  <div class="card-image">
    <figure class="image is-3by2">
      <a href='/sellers/sign_up'> <%= image_tag("seller.png", ) %></a>
    </figure>
  </div>
  <div class="card-content">
    <div class="content">
      <a href="#"> Are you a seller ?</a>
    </div>
    </div>
   </div> 
  </div>
<div class="column is-2">
  </div>
  <div class="column is-3">
  <div class="card">
  <div class="card-image">
    <figure class="image is-3by2">
      <a href='/buyers/sign_up'> <%= image_tag("buyer.png", ) %></a>
    </figure>
  </div>
  <div class="card-content">
    <div class="content">
    <a href="#"> Are you a buyer ?</a>
    </div>
  </div>


 <% end %>


app/views/home/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Announcements</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Description</th>
      <th>Condition</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.title %></td>
        <td><%= announcement.category %></td>
        <td><%= announcement.description %></td>
        <td><%= announcement.condition %></td>
        <td><%= announcement.price %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path %>